### ISSUE TITLE
Doesn't work on Repo's home page on Github

### ISSUE THREAD

**Issue by 31piy** [benscabbia/x-ray#3]
Tried running the script on this page: https://github.com/benscabbia/x-ray. The page gets empty, and the following stack trace is printed in console:

```js
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at <anonymous>:1:263
    at <anonymous>:1:412
```

But strangely, this works on other repos' pages.

**Comment by benscabbia** [comment]
Hi @31piy you might not have seen this (Halfway down [the readme](https://github.com/benscabbia/x-ray#usage)):

![image](https://user-images.githubusercontent.com/7523573/55684276-4a8cd280-5941-11e9-909f-c07180c3453a.png)

It will also break if you tried to trigger it on [this page](https://benscabbia.co.uk/projects/x-ray) on my site (since it also references the script!) :) 

I have closed the issue, but feel free to reopen it if you have any other problems
